### ISSUE TITLE
How to use as library for project?

### ISSUE THREAD

**Issue by Awbmilne** [fido-device-onboard/client-sdk-fidoiot#182]
I am looking to use SDO for my project using cmake as a build system.

What is the easiest way to use this SDK for another project?
I would like to just use the client-sdk-fidoiot as submodule in my project and pull it in with cmake, but the existing build scheme doesnt seem to support that very well. I expect I will have to do some bridging of gaps for storage and network interfaces, but looking for any suggestions or starting points.

**Comment by shrikant1407** [comment]
Can you give more context?
