### ISSUE TITLE
Any plans to develop and share meta-intel-fdo in near future?

### ISSUE THREAD

**Issue by Vishwasrao1** [fido-device-onboard/client-sdk-fidoiot#213]
As you have moved on completely to FDO, just wondering what is the status of , meta-intel-fdo.

**Comment by shrikant1407** [comment]
what is meta-intel-fdo?

**Comment by Vishwasrao1** [comment]
We had a yocto meta layer for Secure Device Onboard. However for FDO the meta layer is not updated. 
link : https://github.com/fido-device-onboard/client-sdk-fidoiot/tree/master/utils/meta-intel-sdo

I can create a meta layer for FDO and send a PR.

**Comment by shrikant1407** [comment]
Sure, you can send us a PR
