### ISSUE TITLE
Supported ROEs

### ISSUE THREAD

**Issue by MarioRossi37** [fido-device-onboard/client-sdk-fidoiot#223]
The ROEs (Restricted Operating Environment) currently supported by this client are TPM (https://github.com/secure-device-onboard/client-sdk-fidoiot/blob/master/docs/tpm.md) and CSE (https://github.com/secure-device-onboard/client-sdk-fidoiot/blob/master/docs/cse.md). 
I was wondering if any others are also supported or will be in future releases.
Specifically, is Qualcomm Trustzone supported (or will be in the future)?

Thanks

**Comment by shrikant1407** [comment]
Currently, we don't support Qualcomm Trustzone. We will let you know if we plan to support it in the future.
